# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
# Starter pipeline
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Yoav''s - Azure Internal Consumption(779b3f2b-726d-430d-a1b7-f8c309b3bbd0)'
    appType: 'functionAppLinux'
    appName: 'bfyoc-yd'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'DOCKER|microsoft/azure-functions-dotnet-core2.0:2.0'
